server:
  port: 8080
  servlet:
    context-path: /zto

spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zto?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


pagehelper:
  helper-dialect: mysql

logging:
  level:
    com:
      yidu:
        zto:
          dao: debug